spring:
  application:
    name: Product API
  datasource:
    url: jdbc:h2:mem:products
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  main:
    lazy-initialization: false
  h2:
    console:
      enabled: true
      path: /h2-console